### ISSUE TITLE
Le total energy est negatif

### ISSUE THREAD

**Issue by maelremrem** [hallard/WeMos-TIC#10]
Apres avoir attendu 24h,
Le total energy est négatif
![image](https://user-images.githubusercontent.com/11769158/191673494-3ef0d804-199b-41fb-b77c-1e1008e47091.png)
J'ai aussi un soucis coté remontée d'info sur HomeAssistant, je peux remonter que le total énergétique et pas la consommation du jour
![image](https://user-images.githubusercontent.com/11769158/191673674-17e7cd2d-ce1d-454a-bbe5-b316e724bf7b.png)
![image](https://user-images.githubusercontent.com/11769158/191673759-3dda24ae-d65b-47c8-8bc3-02f9227af32a.png)
![image](https://user-images.githubusercontent.com/11769158/191673827-d9325e33-854d-4e7a-96f0-da753ed269e5.png)
J'ai bien basculé en mode standard car j'ai un linky
Si vous avez des pistes
(Merci pour le PCB, vraiment super propre mais il ne rentre pas dans le STL fourni si on utilise un écran oled, je vais redesign un modèle 3D pour ça)

**Comment by hallard** [comment]
peut-on clôturer cette issue ?
