### ISSUE TITLE
Is is suitable for running on battery? (Wemos S2)

### ISSUE THREAD

**Issue by Donokami** [hallard/WeMos-TIC#13]
Hey,
And thanks for the project.
Before buying a WeMos-TIC shield, I was asking myself : what is the power consumption of the ESP32 with the WeMos-TIC board and the project running?
Would it be suitable for running the ESP on a battery? I don't have a modular socket on my electric panel, nor any socket around it :/

**Comment by hallard** [comment]
Interesting I did not measured but since it does not sleep and has WiFi at least 100mA so depending on battery capacity should not go above few days.
