### ISSUE TITLE
soldering schema for WeMos Mini S2 ?

### ISSUE THREAD

**Issue by mcarbonneaux** [hallard/WeMos-TIC#7]
I've buy your shield and i whant to be sure how to connect it.

How to solder your adapter to the mini s2 ? use external or internal line ?
You have made the schematique for the esp32 mini dev, but not for the other one...

her : https://github.com/hallard/WeMos-TIC#assembling
When see you table her : https://github.com/hallard/WeMos-TIC#detailed-description

If I understand all pine of your shield are linked for each couple of external/internal line.

If i sold the exterior line of your shield to the external line of S2 like that : 

| Shield Pin | ESP32-S2 | 
|  :---        |    :---:   |
| GND  | GND |
| 5V | VBUS |
| 3V3 | 3V3 |

And normaly the pin function table while be :

| Shield Pin Function | ESP32-S2 | 
|  :---        |    :---:   |
| Téléinfo Rx  | <**GPIO37**> |
| RGB Led (14)     | GPIO07 | 
| I2C SDA (4)     | GPIO33 | 
| I2C SDL  (5)    | GPIO35 | 

LED/SDA/SDL are corresponding but RX are not corresponding to the GPIO of your table (GPIO11 in your table and GPIO37 on the corresponding pin on S2).

![image](https://user-images.githubusercontent.com/8479023/191370043-57b769cd-49ea-4d64-b144-f6990c77af86.png)

![image](https://user-images.githubusercontent.com/8479023/191364976-da7ce34d-9c73-4bd9-ae15-24ea673e8f05.png)

**Comment by hallard** [comment]
If you look at the schematic of the shield (which is the same for all module), Teleinfo RX is connected to `GPIO13` (to leave RX/TX is for serial console) so it's `GPIO11` on S2 and all magic match :-)

Blank text on the PCB (silk) is the one for ESP8266 that may, I must admit do some confusion, but that's the price of compatibility and this is why I put mapping table on the readme.

**Comment by mcarbonneaux** [comment]
<img src="https://user-images.githubusercontent.com/8479023/191567226-3081a072-9f0c-4876-bd08-ecf3a29ad59b.jpg" width="40%" height="40%">&nbsp;
<img src="https://user-images.githubusercontent.com/8479023/191567238-ba0dc867-4f91-4416-af73-ff4b556255c6.jpg" width="40%" height="40%">&nbsp;
<img src="https://user-images.githubusercontent.com/8479023/191567241-ea1da8e8-864c-45a7-b2cf-e6001a8f180e.jpg" width="40%" height="40%">&nbsp;
<img src="https://user-images.githubusercontent.com/8479023/191567242-8d4c44a3-dfa3-4336-8cf2-18911634187c.jpg" width="40%" height="40%">&nbsp;


![D1-Mini-ESP32](https://user-images.githubusercontent.com/8479023/191567226-3081a072-9f0c-4876-bd08-ecf3a29ad59b.jpg)
![Wemos C3 Mini](https://user-images.githubusercontent.com/8479023/191567238-ba0dc867-4f91-4416-af73-ff4b556255c6.jpg)
![WeMos D1 Mini ](https://user-images.githubusercontent.com/8479023/191567241-ea1da8e8-864c-45a7-b2cf-e6001a8f180e.jpg)
![Wemos S2 Mini](https://user-images.githubusercontent.com/8479023/191567242-8d4c44a3-dfa3-4336-8cf2-18911634187c.jpg)

**Comment by hallard** [comment]
Thanks for sharing
